[versions]
kotlin = "2.3.10"
ksp = "2.1.0-1.0.29"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

[libraries]
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.13.3" }
